import type { Metadata } from "next";
import { satoshi } from "./fonts/satoshi";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black scroll-smooth">
      <body
        className={`${satoshi.variable} font-sans antialiased bg-black overflow-x-hidden w-full`}
      >
        {children}
      </body>
    </html>
  );
}
